// Keeps the form limits and usual-range hints together.
export const vitalsLimits = {
  bloodPressureSystolic: {
    label: 'Systolic BP',
    unit: 'mmHg',
    min: 50,
    max: 260,
    usual: '90 to 120',
    placeholder: '120',
    step: '1',
  },
  bloodPressureDiastolic: {
    label: 'Diastolic BP',
    unit: 'mmHg',
    min: 30,
    max: 160,
    usual: '60 to 80',
    placeholder: '80',
    step: '1',
  },
  sugarLevel: {
    label: 'Blood Sugar',
    unit: 'mg/dL',
    min: 20,
    max: 700,
    usual: '70 to 140',
    placeholder: '100',
    step: 'any',
  },
  temperature: {
    label: 'Temperature',
    unit: '°F',
    min: 90,
    max: 110,
    usual: '97 to 99',
    placeholder: '98.6',
    step: 'any',
  },
  heartRate: {
    label: 'Heart Rate',
    unit: 'bpm',
    min: 20,
    max: 250,
    usual: '60 to 100',
    placeholder: '72',
    step: '1',
  },
  pulseRate: {
    label: 'Pulse Rate',
    unit: 'bpm',
    min: 20,
    max: 250,
    usual: '60 to 100',
    placeholder: '72',
    step: '1',
  },
  rbcCount: {
    label: 'RBC Count',
    unit: 'million/µL',
    min: 1,
    max: 10,
    usual: '4.2 to 5.9',
    placeholder: '4.5',
    step: 'any',
  },
  wbcCount: {
    label: 'WBC Count',
    unit: 'cells/µL',
    min: 500,
    max: 100000,
    usual: '4,000 to 11,000',
    placeholder: '7000',
    step: '1',
  },
} as const;
